In [3]:
import torch
import numpy as np

In [4]:
torch.version.__version__

'2.0.1'

检查torch的版本

In [5]:
a = torch.ones(3,3)
a

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [6]:
a[0,1]=2
a

tensor([[1., 2., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

两个索引分别表示行和列

In [7]:
b = torch.ones(3,3)
a+b

tensor([[2., 3., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [8]:
torch.cuda.is_available()

False

In [12]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [15]:
np_array = np.array(data)
print(np_array)
x_np = torch.tensor(np_array) #复制numpy数组的数据
print(x_np)

[[1 2]
 [3 4]]
tensor([[1, 2],
        [3, 4]])


In [18]:
x1 = torch.ones_like(x_data)
print(x1)
x2 = torch.rand_like(x_data,dtype=float) #这个方法只适用于浮点型的张量，对于long类型的张量不适用
print(x2)

tensor([[1, 1],
        [1, 1]])
tensor([[0.6889, 0.1499],
        [0.8329, 0.0017]], dtype=torch.float64)


In [21]:
shape = (2,3) #shape = (2,3,)效果一样
rand_tesor = torch.rand(shape)
print(rand_tesor)
ones_tensor = torch.ones(shape)
print(ones_tensor)

tensor([[0.3455, 0.1334, 0.3109],
        [0.2169, 0.4606, 0.4813]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [23]:
tensor = torch.rand(3,4)
print(tensor.shape,tensor.dtype,tensor.device)

torch.Size([3, 4]) torch.float32 cpu


In [24]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')

tensor默认在cpu运行，需要以上语句将其移动到gpu运行

In [26]:
tensor = torch.rand(4,4)
print(tensor)
print("first row:",tensor[0])
print("last row:",tensor[-1])
print("first column:",tensor[:,0])
print("last col:",tensor[...,-1])
print("last?",tensor[:,-1])
tensor[:,1]=0 #注意这是第二列！
print(tensor)

tensor([[0.9037, 0.4141, 0.1843, 0.8545],
        [0.4442, 0.2585, 0.7374, 0.7854],
        [0.0307, 0.7404, 0.6525, 0.7396],
        [0.1124, 0.4544, 0.6622, 0.2817]])
first row: tensor([0.9037, 0.4141, 0.1843, 0.8545])
last row: tensor([0.1124, 0.4544, 0.6622, 0.2817])
first column: tensor([0.9037, 0.4442, 0.0307, 0.1124])
last col: tensor([0.8545, 0.7854, 0.7396, 0.2817])
last? tensor([0.8545, 0.7854, 0.7396, 0.2817])
tensor([[0.9037, 0.0000, 0.1843, 0.8545],
        [0.4442, 0.0000, 0.7374, 0.7854],
        [0.0307, 0.0000, 0.6525, 0.7396],
        [0.1124, 0.0000, 0.6622, 0.2817]])


In [34]:
t1 = torch.cat([tensor,tensor,tensor])
print(t1) #效果与dim=0相同，竖着拼接
t2 = torch.cat([tensor,tensor,tensor],dim = 1)
print(t2) #横着拼接
t3 = torch.cat([tensor,tensor,tensor],dim= 0)
print(t3)

tensor([[0.9037, 0.0000, 0.1843, 0.8545],
        [0.4442, 0.0000, 0.7374, 0.7854],
        [0.0307, 0.0000, 0.6525, 0.7396],
        [0.1124, 0.0000, 0.6622, 0.2817],
        [0.9037, 0.0000, 0.1843, 0.8545],
        [0.4442, 0.0000, 0.7374, 0.7854],
        [0.0307, 0.0000, 0.6525, 0.7396],
        [0.1124, 0.0000, 0.6622, 0.2817],
        [0.9037, 0.0000, 0.1843, 0.8545],
        [0.4442, 0.0000, 0.7374, 0.7854],
        [0.0307, 0.0000, 0.6525, 0.7396],
        [0.1124, 0.0000, 0.6622, 0.2817]])
tensor([[0.9037, 0.0000, 0.1843, 0.8545, 0.9037, 0.0000, 0.1843, 0.8545, 0.9037,
         0.0000, 0.1843, 0.8545],
        [0.4442, 0.0000, 0.7374, 0.7854, 0.4442, 0.0000, 0.7374, 0.7854, 0.4442,
         0.0000, 0.7374, 0.7854],
        [0.0307, 0.0000, 0.6525, 0.7396, 0.0307, 0.0000, 0.6525, 0.7396, 0.0307,
         0.0000, 0.6525, 0.7396],
        [0.1124, 0.0000, 0.6622, 0.2817, 0.1124, 0.0000, 0.6622, 0.2817, 0.1124,
         0.0000, 0.6622, 0.2817]])
tensor([[0.9037, 0.0000, 0.1843, 0

In [41]:
y1 = tensor @ tensor.T #矩阵乘法,y1=y2
y2 = torch.matmul(tensor,tensor.T)
print(y1,y2)

y3 = tensor * tensor.T #逐个元素相乘,y3=y4
y4 = torch.mul(tensor,tensor.T)
print(y3,y4)

tensor([[1.5808, 1.2084, 0.7800, 0.4643],
        [1.2084, 1.3580, 1.0757, 0.7595],
        [0.7800, 1.0757, 0.9736, 0.6439],
        [0.4643, 0.7595, 0.6439, 0.5305]]) tensor([[1.5808, 1.2084, 0.7800, 0.4643],
        [1.2084, 1.3580, 1.0757, 0.7595],
        [0.7800, 1.0757, 0.9736, 0.6439],
        [0.4643, 0.7595, 0.6439, 0.5305]])
tensor([[0.8167, 0.0000, 0.0057, 0.0960],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0057, 0.0000, 0.4257, 0.4898],
        [0.0960, 0.0000, 0.4898, 0.0793]]) tensor([[0.8167, 0.0000, 0.0057, 0.0960],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0057, 0.0000, 0.4257, 0.4898],
        [0.0960, 0.0000, 0.4898, 0.0793]])


In [42]:
agg = tensor.sum()
agg_item = agg.item() #将单元素张量转换为数字
print(agg,agg_item,type(agg_item))

tensor(6.3886) 6.3885698318481445 <class 'float'>


In [48]:
print(tensor,"\n")
print(tensor)
tensor.add_(5) #每个元素增加5（会直接修改原始的张量）
print(tensor)

tensor([[15.9037, 15.0000, 15.1843, 15.8545],
        [15.4442, 15.0000, 15.7374, 15.7854],
        [15.0307, 15.0000, 15.6525, 15.7396],
        [15.1124, 15.0000, 15.6622, 15.2817]]) 

tensor([[15.9037, 15.0000, 15.1843, 15.8545],
        [15.4442, 15.0000, 15.7374, 15.7854],
        [15.0307, 15.0000, 15.6525, 15.7396],
        [15.1124, 15.0000, 15.6622, 15.2817]])
tensor([[20.9037, 20.0000, 20.1843, 20.8545],
        [20.4442, 20.0000, 20.7374, 20.7854],
        [20.0307, 20.0000, 20.6525, 20.7396],
        [20.1124, 20.0000, 20.6622, 20.2817]])


In [50]:
t = torch.ones(5)
n = t.numpy() #记得加括号！
print(t,n)

tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]


In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)
#x_np = torch.tensor(np_array)复制numpy的数据，而torch.from_numpy(n)与numpy数组共享内存